title: Umuterankuru
author: GitHub User
email: your-email@domain.com
copyright: © 2019 snow-blade
description: > # this means to ignore newlines until "show_excerpts:"
  Poetry written by a noble fool.

show_excerpts: false # set to true to show excerpts on the homepage

lin:
  date_format: "%b %-d, %Y"

  # path to the author avatar image
  avatar_path: assets/images/avatar.jpg

  # generate social links
  social_links:
    twitter: tweepcoder
    github:  snow-blade
    medium:  freemanirabaruta
    rss: rss
    dribbble: jekyll
    facebook: freeman.irabaruta
    flickr:   jekyll
    instagram: ucode_257
    linkedin: freeman-irabaruta-7213981a0
    pinterest: jekyll
    youtube_user: jekyll
    youtube_channel: UC8CXR0-3I70i1tfPg1PAE1g
    telegram: Snow_blade
    googleplus: +jekyll
    keybase: jekyll

theme: lin

plugins:
 - jekyll-feed
 - jekyll-seo-tag
